# 📊 What Makes a TV Series Popular?
### Student Data Lab (IMDb + Netflix + TMDb)

You will analyze real TV series data to discover what makes shows popular.

In [2]:
!make init
!python -m netflix.fetch
!python -m netflix.build

===============================================================================
Initializing local development environment. This will verify and set up your
Python virtual environment, install all 3rd-party package requirements.
This may take a few minutes...
===============================================================================


===============================================================================
Initialization complete!
===============================================================================
make python-init
===============================================================================
Initializing Python virtual environment and installing dependencies. This may take a few minutes...
===============================================================================
rm -r -f venv && \
	mkdir -p .pypi_cache && \
	make check-python

===============================================================================
Verifying that Python python3.13 is installed ...
===============================================================================

make python-clean && \
	npm install && \
	python3.13 -m venv venv && \
	source venv/bin/activate && \
	python3.13 -m pip install pip==25.3 setuptools wheel pip-tools && \
	PIP_CACHE_DIR=.pypi_cache python3.13 -m pip install -r requirements/local.txt

===============================================================================
Cleaning Python virtual environment and __pycache__ directories ...
===============================================================================

rm -rf venv
find ./netflix/ -name __pycache__ -type d -exec rm -rf {} +
⠙⠹⠸⠼
up to date, audited 471 packages in 599ms
⠼
⠼100 packages are looking for funding
⠼  run `npm fund` for details
⠼
1 high severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
⠼Collecting pip==25.3
  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Collecting setuptools
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting wheel
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting pip-tools
  Using cached pip_tools-7.5.3-py3-none-any.whl.metadata (27 kB)
Collecting packaging>=24.0 (from wheel)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting build>=1.0.0 (from pip-tools)
  Using cached build-1.5.0-py3-none-any.whl.metadata (5.7 kB)
Collecting click>=8 (from pip-tools)
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting pyproject_hooks (from pip-tools)
  Using cached pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Using cached pip-25.3-py3-none-any.whl (1.8 MB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached pip_tools-7.5.3-py3-none-any.whl (71 kB)
Using cached build-1.5.0-py3-none-any.whl (26 kB)
Using cached click-8.4.1-py3-none-any.whl (116 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Using cached pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Installing collected packages: setuptools, pyproject_hooks, pip, packaging, click, wheel, build, pip-tools
  Attempting uninstall: pip━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/8 [setuptools]
    Found existing installation: pip 25.2━━━━━━━━━ 0/8 [setuptools]
    Uninstalling pip-25.2:━━━━━━━━━━━━━━━━━━━━━━━━ 0/8 [setuptools]
      Successfully uninstalled pip-25.2━━━━━━━━━━━ 0/8 [setuptools]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [pip-tools]━ 7/8 [pip-tools]
Successfully installed build-1.5.0 click-8.4.1 packaging-26.2 pip-25.3 pip-tools-7.5.3 pyproject_hooks-1.2.0 setuptools-82.0.1 wheel-0.47.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Collecting annotated-doc==0.0.4 (from -r requirements/local.txt (line 7))
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio==4.13.0 (from -r requirements/local.txt (line 9))
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting appnope==0.1.4 (from -r requirements/local.txt (line 13))
  Using cached appnope-0.1.4-py2.py3-none-any.whl.metadata (908 bytes)
Collecting argon2-cffi==25.1.0 (from -r requirements/local.txt (line 15))
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting argon2-cffi-bindings==25.1.0 (from -r requirements/local.txt (line 17))
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting arrow==1.4.0 (from -r requirements/local.txt (line 19))
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Collecting ast-serialize==0.5.0 (from -r requirements/local.txt (line 21))
  Using cached ast_serialize-0.5.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (1.3 kB)
Collecting astroid==4.0.4 (from -r requirements/local.txt (line 23))
  Using cached astroid-4.0.4-py3-none-any.whl.metadata (4.4 kB)
Collecting asttokens==3.0.1 (from -r requirements/local.txt (line 25))
  Using cached asttokens-3.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting async-lru==2.3.0 (from -r requirements/local.txt (line 27))
  Using cached async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting attrs==26.1.0 (from -r requirements/local.txt (line 29))
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting babel==2.18.0 (from -r requirements/local.txt (line 33))
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting bandit==1.9.4 (from -r requirements/local.txt (line 35))
  Using cached bandit-1.9.4-py3-none-any.whl.metadata (7.1 kB)
Collecting beautifulsoup4==4.15.0 (from -r requirements/local.txt (line 37))
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting black==26.5.1 (from -r requirements/local.txt (line 41))
  Using cached black-26.5.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (95 kB)
Collecting bleach==6.4.0 (from bleach[css]==6.4.0->-r requirements/local.txt (line 43))
  Using cached bleach-6.4.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: build==1.5.0 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 47)) (1.5.0)
Collecting cachetools==7.1.4 (from -r requirements/local.txt (line 49))
  Using cached cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Collecting certifi==2026.5.20 (from -r requirements/local.txt (line 51))
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi==2.0.0 (from -r requirements/local.txt (line 56))
  Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.6 kB)
Collecting cfgv==3.5.0 (from -r requirements/local.txt (line 58))
  Using cached cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting charset-normalizer==3.4.7 (from -r requirements/local.txt (line 60))
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Requirement already satisfied: click==8.4.1 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 62)) (8.4.1)
Collecting cloudpickle==3.1.2 (from -r requirements/local.txt (line 66))
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting codespell==2.4.2 (from -r requirements/local.txt (line 68))
  Using cached codespell-2.4.2-py3-none-any.whl.metadata (15 kB)
Collecting colorama==0.4.6 (from -r requirements/local.txt (line 70))
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting comm==0.2.3 (from -r requirements/local.txt (line 72))
  Using cached comm-0.2.3-py3-none-any.whl.metadata (3.7 kB)
Collecting contourpy==1.3.3 (from -r requirements/local.txt (line 74))
  Using cached contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting coverage==7.14.1 (from -r requirements/local.txt (line 76))
  Using cached coverage-7.14.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.6 kB)

Collecting cssselect==1.4.0 (from -r requirements/local.txt (line 78))
  Using cached cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting cycler==0.12.1 (from -r requirements/local.txt (line 80))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting debugpy==1.8.21 (from -r requirements/local.txt (line 82))
  Using cached debugpy-1.8.21-cp313-cp313-macosx_15_0_universal2.whl.metadata (1.4 kB)
Collecting decorator==5.3.1 (from -r requirements/local.txt (line 84))
  Using cached decorator-5.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting defusedxml==0.7.1 (from -r requirements/local.txt (line 86))
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting dill==0.4.1 (from -r requirements/local.txt (line 88))
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting distlib==0.4.3 (from -r requirements/local.txt (line 90))
  Using cached distlib-0.4.3-py2.py3-none-any.whl.metadata (5.3 kB)
Collecting duckdb==1.5.3 (from -r requirements/local.txt (line 92))
  Using cached duckdb-1.5.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.2 kB)
Collecting executing==2.2.1 (from -r requirements/local.txt (line 94))
  Using cached executing-2.2.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting fastjsonschema==2.21.2 (from -r requirements/local.txt (line 96))
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting filelock==3.29.4 (from -r requirements/local.txt (line 98))
  Using cached filelock-3.29.4-py3-none-any.whl.metadata (2.0 kB)
Collecting flake8==7.3.0 (from -r requirements/local.txt (line 103))
  Using cached flake8-7.3.0-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting flake8-coding==1.3.2 (from -r requirements/local.txt (line 107))
  Using cached flake8_coding-1.3.2-py2.py3-none-any.whl.metadata (3.1 kB)
Collecting fonttools==4.63.0 (from -r requirements/local.txt (line 109))
  Using cached fonttools-4.63.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (118 kB)
Collecting fqdn==1.5.1 (from -r requirements/local.txt (line 111))
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting h11==0.16.0 (from -r requirements/local.txt (line 113))
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting httpcore==1.0.9 (from -r requirements/local.txt (line 115))
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting httpx==0.28.1 (from -r requirements/local.txt (line 117))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting identify==2.6.19 (from -r requirements/local.txt (line 119))
  Using cached identify-2.6.19-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting idna==3.18 (from -r requirements/local.txt (line 121))
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting iniconfig==2.3.0 (from -r requirements/local.txt (line 127))
  Using cached iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting ipykernel==7.3.0 (from -r requirements/local.txt (line 129))
  Using cached ipykernel-7.3.0-py3-none-any.whl.metadata (4.5 kB)
Collecting ipython==9.14.1 (from -r requirements/local.txt (line 133))
  Using cached ipython-9.14.1-py3-none-any.whl.metadata (4.7 kB)
Collecting ipython-pygments-lexers==1.1.1 (from -r requirements/local.txt (line 135))
  Using cached ipython_pygments_lexers-1.1.1-py3-none-any.whl.metadata (1.1 kB)
Collecting isoduration==20.11.0 (from -r requirements/local.txt (line 137))
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting isort==8.0.1 (from -r requirements/local.txt (line 139))
  Using cached isort-8.0.1-py3-none-any.whl.metadata (11 kB)
Collecting jedi==0.20.0 (from -r requirements/local.txt (line 141))
  Using cached jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Collecting jinja2==3.1.6 (from -r requirements/local.txt (line 143))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting joblib==1.5.3 (from -r requirements/local.txt (line 149))
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting json5==0.14.0 (from -r requirements/local.txt (line 151))
  Using cached json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonpointer==3.1.1 (from -r requirements/local.txt (line 153))
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting jsonschema==4.26.0 (from jsonschema[format-nongpl]==4.26.0->-r requirements/local.txt (line 155))
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting jsonschema-specifications==2025.9.1 (from -r requirements/local.txt (line 160))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-client==8.9.1 (from -r requirements/local.txt (line 162))
  Using cached jupyter_client-8.9.1-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter-core==5.9.1 (from -r requirements/local.txt (line 167))
  Using cached jupyter_core-5.9.1-py3-none-any.whl.metadata (1.5 kB)
Collecting jupyter-events==0.12.1 (from -r requirements/local.txt (line 176))
  Using cached jupyter_events-0.12.1-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-lsp==2.3.1 (from -r requirements/local.txt (line 178))
  Using cached jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server==2.19.0 (from -r requirements/local.txt (line 180))
  Using cached jupyter_server-2.19.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter-server-terminals==0.5.4 (from -r requirements/local.txt (line 186))
  Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab==4.5.8 (from -r requirements/local.txt (line 188))
  Using cached jupyterlab-4.5.8-py3-none-any.whl.metadata (16 kB)
Collecting jupyterlab-pygments==0.3.0 (from -r requirements/local.txt (line 190))
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting jupyterlab-server==2.28.0 (from -r requirements/local.txt (line 192))
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupytext==1.19.3 (from -r requirements/local.txt (line 194))
  Using cached jupytext-1.19.3-py3-none-any.whl.metadata (15 kB)
Collecting kaggle==2.2.1 (from -r requirements/local.txt (line 196))
  Using cached kaggle-2.2.1-py3-none-any.whl.metadata (16 kB)
Collecting kagglesdk==0.1.30 (from -r requirements/local.txt (line 198))
  Using cached kagglesdk-0.1.30-py3-none-any.whl.metadata (13 kB)
Collecting kiwisolver==1.5.0 (from -r requirements/local.txt (line 200))
  Using cached kiwisolver-1.5.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.1 kB)
Collecting lark==1.3.1 (from -r requirements/local.txt (line 202))
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting librt==0.11.0 (from -r requirements/local.txt (line 204))
  Using cached librt-0.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (1.3 kB)
Collecting llvmlite==0.47.0 (from -r requirements/local.txt (line 206))
  Using cached llvmlite-0.47.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (5.0 kB)
Collecting markdown-it-py==4.2.0 (from -r requirements/local.txt (line 210))
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting markupsafe==3.0.3 (from -r requirements/local.txt (line 215))
  Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting matplotlib==3.11.0 (from -r requirements/local.txt (line 219))
  Using cached matplotlib-3.11.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (80 kB)
Collecting matplotlib-inline==0.2.2 (from -r requirements/local.txt (line 223))
  Using cached matplotlib_inline-0.2.2-py3-none-any.whl.metadata (2.4 kB)
Collecting mccabe==0.7.0 (from -r requirements/local.txt (line 227))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting mdit-py-plugins==0.6.1 (from -r requirements/local.txt (line 231))
  Using cached mdit_py_plugins-0.6.1-py3-none-any.whl.metadata (2.9 kB)
Collecting mdurl==0.1.2 (from -r requirements/local.txt (line 233))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting mistune==3.2.1 (from -r requirements/local.txt (line 235))
  Using cached mistune-3.2.1-py3-none-any.whl.metadata (1.9 kB)
Collecting mypy==2.1.0 (from -r requirements/local.txt (line 237))
  Using cached mypy-2.1.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)

Collecting mypy-extensions==1.1.0 (from -r requirements/local.txt (line 241))
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting narwhals==2.22.1 (from -r requirements/local.txt (line 246))
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting nbclient==0.11.0 (from -r requirements/local.txt (line 248))
  Using cached nbclient-0.11.0-py3-none-any.whl.metadata (7.3 kB)
Collecting nbconvert==7.17.1 (from -r requirements/local.txt (line 250))
  Using cached nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Collecting nbformat==5.10.4 (from -r requirements/local.txt (line 252))
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting nest-asyncio2==1.7.2 (from -r requirements/local.txt (line 258))
  Using cached nest_asyncio2-1.7.2-py3-none-any.whl.metadata (6.3 kB)
Collecting nodeenv==1.10.0 (from -r requirements/local.txt (line 260))
  Using cached nodeenv-1.10.0-py2.py3-none-any.whl.metadata (24 kB)
Collecting notebook-shim==0.2.4 (from -r requirements/local.txt (line 262))
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting numba==0.65.1 (from -r requirements/local.txt (line 264))
  Using cached numba-0.65.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (2.9 kB)
Collecting numpy==2.4.6 (from -r requirements/local.txt (line 266))
  Using cached numpy-2.4.6-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: packaging==26.2 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 278)) (26.2)
Collecting pandas==2.3.3 (from -r requirements/local.txt (line 296))
  Using cached pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting pandas-stubs==3.0.3.260530 (from -r requirements/local.txt (line 301))
  Using cached pandas_stubs-3.0.3.260530-py3-none-any.whl.metadata (11 kB)
Collecting pandocfilters==1.5.1 (from -r requirements/local.txt (line 303))
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting parso==0.8.7 (from -r requirements/local.txt (line 305))
  Using cached parso-0.8.7-py2.py3-none-any.whl.metadata (8.2 kB)
Collecting pathspec==1.1.1 (from -r requirements/local.txt (line 307))
  Using cached pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting pexpect==4.9.0 (from -r requirements/local.txt (line 311))
  Using cached pexpect-4.9.0-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting pillow==12.2.0 (from -r requirements/local.txt (line 313))
  Using cached pillow-12.2.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.8 kB)
Requirement already satisfied: pip-tools==7.5.3 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 315)) (7.5.3)
Collecting platformdirs==4.10.0 (from -r requirements/local.txt (line 317))
  Using cached platformdirs-4.10.0-py3-none-any.whl.metadata (5.5 kB)
Collecting pluggy==1.6.0 (from -r requirements/local.txt (line 325))
  Using cached pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pre-commit==4.6.0 (from -r requirements/local.txt (line 329))
  Using cached pre_commit-4.6.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting prometheus-client==0.25.0 (from -r requirements/local.txt (line 331))
  Using cached prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting prompt-toolkit==3.0.52 (from -r requirements/local.txt (line 333))
  Using cached prompt_toolkit-3.0.52-py3-none-any.whl.metadata (6.4 kB)
Collecting protobuf==6.33.6 (from -r requirements/local.txt (line 335))
  Using cached protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting psutil==7.2.2 (from -r requirements/local.txt (line 339))
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting ptyprocess==0.7.0 (from -r requirements/local.txt (line 343))
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting pure-eval==0.2.3 (from -r requirements/local.txt (line 347))
  Using cached pure_eval-0.2.3-py3-none-any.whl.metadata (6.3 kB)
Collecting pycodestyle==2.14.0 (from -r requirements/local.txt (line 349))
  Using cached pycodestyle-2.14.0-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting pycparser==3.0 (from -r requirements/local.txt (line 351))
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pyflakes==3.4.0 (from -r requirements/local.txt (line 353))
  Using cached pyflakes-3.4.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting pygments==2.20.0 (from -r requirements/local.txt (line 355))
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pylint==4.0.6 (from -r requirements/local.txt (line 362))
  Using cached pylint-4.0.6-py3-none-any.whl.metadata (12 kB)
Collecting pylint-django==2.7.0 (from -r requirements/local.txt (line 367))
  Using cached pylint_django-2.7.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pylint-plugin-utils==0.9.0 (from -r requirements/local.txt (line 369))
  Using cached pylint_plugin_utils-0.9.0-py3-none-any.whl.metadata (2.8 kB)
Collecting pyparsing==3.3.2 (from -r requirements/local.txt (line 371))
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting pyproject-api==1.10.1 (from -r requirements/local.txt (line 373))
  Using cached pyproject_api-1.10.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyproject-hooks==1.2.0 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 375)) (1.2.0)
Collecting pytest==9.1.0 (from -r requirements/local.txt (line 379))
  Using cached pytest-9.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-mock==3.15.1 (from -r requirements/local.txt (line 383))
  Using cached pytest_mock-3.15.1-py3-none-any.whl.metadata (3.9 kB)
Collecting python-dateutil==2.9.0.post0 (from -r requirements/local.txt (line 385))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting python-discovery==1.4.2 (from -r requirements/local.txt (line 392))
  Using cached python_discovery-1.4.2-py3-none-any.whl.metadata (5.6 kB)
Collecting python-dotenv==1.2.2 (from -r requirements/local.txt (line 396))
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Collecting python-json-logger==4.1.0 (from -r requirements/local.txt (line 400))
  Using cached python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting python-slugify==8.0.4 (from -r requirements/local.txt (line 402))
  Using cached python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting pytokens==0.4.1 (from -r requirements/local.txt (line 404))
  Using cached pytokens-0.4.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting pytz==2026.2 (from -r requirements/local.txt (line 406))
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting pyyaml==6.0.3 (from -r requirements/local.txt (line 408))
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting pyzmq==27.1.0 (from -r requirements/local.txt (line 414))
  Using cached pyzmq-27.1.0-cp312-abi3-macosx_10_15_universal2.whl.metadata (6.0 kB)
Collecting rapidfuzz==3.14.5 (from -r requirements/local.txt (line 419))
  Using cached rapidfuzz-3.14.5-cp313-cp313-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting referencing==0.37.0 (from -r requirements/local.txt (line 421))
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting requests==2.34.2 (from -r requirements/local.txt (line 426))
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting rfc3339-validator==0.1.4 (from -r requirements/local.txt (line 432))
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator==0.1.1 (from -r requirements/local.txt (line 436))
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting rfc3987-syntax==1.1.0 (from -r requirements/local.txt (line 440))
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting rich==15.0.0 (from -r requirements/local.txt (line 442))
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting rpds-py==2026.5.1 (from -r requirements/local.txt (line 446))

  Using cached rpds_py-2026.5.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting scikit-learn==1.9.0 (from -r requirements/local.txt (line 450))
  Using cached scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting scipy==1.17.1 (from -r requirements/local.txt (line 454))
  Using cached scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting seaborn==0.13.2 (from -r requirements/local.txt (line 459))
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting send2trash==2.1.0 (from -r requirements/local.txt (line 461))
  Using cached send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting shap==0.52.0 (from -r requirements/local.txt (line 463))
  Using cached shap-0.52.0-cp312-abi3-macosx_11_0_arm64.whl.metadata (26 kB)
Collecting shellingham==1.5.4 (from -r requirements/local.txt (line 465))
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting six==1.17.0 (from -r requirements/local.txt (line 467))
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting slicer==0.0.8 (from -r requirements/local.txt (line 471))
  Using cached slicer-0.0.8-py3-none-any.whl.metadata (4.0 kB)
Collecting soupsieve==2.8.4 (from -r requirements/local.txt (line 473))
  Using cached soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting stack-data==0.6.3 (from -r requirements/local.txt (line 475))
  Using cached stack_data-0.6.3-py3-none-any.whl.metadata (18 kB)
Collecting stevedore==5.8.0 (from -r requirements/local.txt (line 477))
  Using cached stevedore-5.8.0-py3-none-any.whl.metadata (2.3 kB)
Collecting terminado==0.18.1 (from -r requirements/local.txt (line 479))
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting text-unidecode==1.3 (from -r requirements/local.txt (line 483))
  Using cached text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting threadpoolctl==3.6.0 (from -r requirements/local.txt (line 485))
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting tinycss2==1.5.1 (from -r requirements/local.txt (line 487))
  Using cached tinycss2-1.5.1-py3-none-any.whl.metadata (3.0 kB)
Collecting tomli-w==1.2.0 (from -r requirements/local.txt (line 489))
  Using cached tomli_w-1.2.0-py3-none-any.whl.metadata (5.7 kB)
Collecting tomlkit==0.15.0 (from -r requirements/local.txt (line 491))
  Using cached tomlkit-0.15.0-py3-none-any.whl.metadata (2.8 kB)
Collecting tornado==6.5.7 (from -r requirements/local.txt (line 493))
  Using cached tornado-6.5.7-cp39-abi3-macosx_10_9_universal2.whl.metadata (2.8 kB)
Collecting tox==4.55.1 (from -r requirements/local.txt (line 500))
  Using cached tox-4.55.1-py3-none-any.whl.metadata (3.8 kB)
Collecting tqdm==4.68.2 (from -r requirements/local.txt (line 502))
  Using cached tqdm-4.68.2-py3-none-any.whl.metadata (58 kB)
Collecting traitlets==5.15.1 (from -r requirements/local.txt (line 507))
  Using cached traitlets-5.15.1-py3-none-any.whl.metadata (10 kB)
Collecting typer==0.26.7 (from -r requirements/local.txt (line 520))
  Using cached typer-0.26.7-py3-none-any.whl.metadata (16 kB)
Collecting types-cachetools==7.0.0.20260518 (from -r requirements/local.txt (line 522))
  Using cached types_cachetools-7.0.0.20260518-py3-none-any.whl.metadata (1.8 kB)
Collecting types-html5lib==1.1.11.20260518 (from -r requirements/local.txt (line 524))
  Using cached types_html5lib-1.1.11.20260518-py3-none-any.whl.metadata (1.8 kB)
Collecting types-lxml==2026.2.16 (from -r requirements/local.txt (line 526))
  Using cached types_lxml-2026.2.16-py3-none-any.whl.metadata (11 kB)
Collecting types-requests==2.33.0.20260518 (from -r requirements/local.txt (line 528))
  Using cached types_requests-2.33.0.20260518-py3-none-any.whl.metadata (2.2 kB)
Collecting types-tqdm==4.68.0.20260608 (from -r requirements/local.txt (line 532))
  Using cached types_tqdm-4.68.0.20260608-py3-none-any.whl.metadata (1.7 kB)
Collecting types-webencodings==0.5.0.20260408 (from -r requirements/local.txt (line 534))
  Using cached types_webencodings-0.5.0.20260408-py3-none-any.whl.metadata (1.8 kB)
Collecting typing-extensions==4.15.0 (from -r requirements/local.txt (line 536))
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting tzdata==2026.2 (from -r requirements/local.txt (line 542))
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting uri-template==1.3.0 (from -r requirements/local.txt (line 546))
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting urllib3==2.7.0 (from -r requirements/local.txt (line 548))
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting virtualenv==21.5.0 (from -r requirements/local.txt (line 553))
  Using cached virtualenv-21.5.0-py3-none-any.whl.metadata (3.4 kB)
Collecting wcwidth==0.8.1 (from -r requirements/local.txt (line 557))
  Using cached wcwidth-0.8.1-py3-none-any.whl.metadata (43 kB)
Collecting webcolors==25.10.0 (from -r requirements/local.txt (line 559))
  Using cached webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting webencodings==0.5.1 (from -r requirements/local.txt (line 561))
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting websocket-client==1.9.0 (from -r requirements/local.txt (line 565))
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: wheel==0.47.0 in ./venv/lib/python3.13/site-packages (from -r requirements/local.txt (line 567)) (0.47.0)
Requirement already satisfied: setuptools>=41.1.0 in ./venv/lib/python3.13/site-packages (from jupyterlab==4.5.8->-r requirements/local.txt (line 188)) (82.0.1)
Requirement already satisfied: pip>=22.2 in ./venv/lib/python3.13/site-packages (from pip-tools==7.5.3->-r requirements/local.txt (line 315)) (25.3)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached appnope-0.1.4-py2.py3-none-any.whl (4.3 kB)
Using cached argon2_cffi-25.1.0-py3-none-any.whl (14 kB)
Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-macosx_11_0_arm64.whl (31 kB)
Using cached arrow-1.4.0-py3-none-any.whl (68 kB)
Using cached ast_serialize-0.5.0-cp39-abi3-macosx_11_0_arm64.whl (1.2 MB)
Using cached astroid-4.0.4-py3-none-any.whl (276 kB)
Using cached asttokens-3.0.1-py3-none-any.whl (27 kB)
Using cached async_lru-2.3.0-py3-none-any.whl (8.4 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached babel-2.18.0-py3-none-any.whl (10.2 MB)
Using cached bandit-1.9.4-py3-none-any.whl (134 kB)
Using cached beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Using cached black-26.5.1-cp313-cp313-macosx_11_0_arm64.whl (1.8 MB)
Using cached pytokens-0.4.1-cp313-cp313-macosx_11_0_arm64.whl (160 kB)
Using cached bleach-6.4.0-py3-none-any.whl (165 kB)
Using cached cachetools-7.1.4-py3-none-any.whl (16 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached cffi-2.0.0-cp313-cp313-macosx_11_0_arm64.whl (181 kB)
Using cached cfgv-3.5.0-py2.py3-none-any.whl (7.4 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached codespell-2.4.2-py3-none-any.whl (353 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached comm-0.2.3-py3-none-any.whl (7.3 kB)
Using cached contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl (274 kB)
Using cached coverage-7.14.1-cp313-cp313-macosx_11_0_arm64.whl (220 kB)
Using cached cssselect-1.4.0-py3-none-any.whl (18 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached debugpy-1.8.21-cp313-cp313-macosx_15_0_universal2.whl (2.5 MB)
Using cached decorator-5.3.1-py3-none-any.whl (10 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached distlib-0.4.3-py2.py3-none-any.whl (470 kB)
Using cached duckdb-1.5.3-cp313-cp313-macosx_11_0_arm64.whl (15.4 MB)
Using cached executing-2.2.1-py2.py3-none-any.whl (28 kB)
Using cached fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Using cached filelock-3.29.4-py3-none-any.whl (42 kB)
Using cached flake8-7.3.0-py2.py3-none-any.whl (57 kB)
Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Using cached pycodestyle-2.14.0-py2.py3-none-any.whl (31 kB)
Using cached pyflakes-3.4.0-py2.py3-none-any.whl (63 kB)
Using cached flake8_coding-1.3.2-py2.py3-none-any.whl (7.6 kB)
Using cached fonttools-4.63.0-cp313-cp313-macosx_10_13_universal2.whl (2.9 MB)
Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached identify-2.6.19-py2.py3-none-any.whl (99 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Using cached ipykernel-7.3.0-py3-none-any.whl (120 kB)
Using cached ipython-9.14.1-py3-none-any.whl (627 kB)
Using cached prompt_toolkit-3.0.52-py3-none-any.whl (391 kB)
Using cached ipython_pygments_lexers-1.1.1-py3-none-any.whl (8.1 kB)
Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
Using cached isort-8.0.1-py3-none-any.whl (89 kB)
Using cached jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
Using cached parso-0.8.7-py2.py3-none-any.whl (107 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached json5-0.14.0-py3-none-any.whl (36 kB)
Using cached jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached jupyter_client-8.9.1-py3-none-any.whl (109 kB)
Using cached jupyter_core-5.9.1-py3-none-any.whl (29 kB)
Using cached jupyter_events-0.12.1-py3-none-any.whl (19 kB)
Using cached jupyter_lsp-2.3.1-py3-none-any.whl (77 kB)
Using cached jupyter_server-2.19.0-py3-none-any.whl (392 kB)
Using cached jupyter_server_terminals-0.5.4-py3-none-any.whl (13 kB)
Using cached jupyterlab-4.5.8-py3-none-any.whl (12.4 MB)
Using cached jupyterlab_server-2.28.0-py3-none-any.whl (59 kB)
Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Using cached jupytext-1.19.3-py3-none-any.whl (170 kB)

Using cached kaggle-2.2.1-py3-none-any.whl (132 kB)
Using cached kagglesdk-0.1.30-py3-none-any.whl (231 kB)
Using cached kiwisolver-1.5.0-cp313-cp313-macosx_11_0_arm64.whl (64 kB)
Using cached lark-1.3.1-py3-none-any.whl (113 kB)
Using cached librt-0.11.0-cp313-cp313-macosx_11_0_arm64.whl (143 kB)
Using cached llvmlite-0.47.0-cp313-cp313-macosx_12_0_arm64.whl (37.2 MB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Using cached matplotlib-3.11.0-cp313-cp313-macosx_11_0_arm64.whl (9.3 MB)
Using cached matplotlib_inline-0.2.2-py3-none-any.whl (9.5 kB)
Using cached mdit_py_plugins-0.6.1-py3-none-any.whl (66 kB)
Using cached mistune-3.2.1-py3-none-any.whl (53 kB)
Using cached mypy-2.1.0-cp313-cp313-macosx_11_0_arm64.whl (13.7 MB)
Using cached mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached nbclient-0.11.0-py3-none-any.whl (25 kB)
Using cached nbconvert-7.17.1-py3-none-any.whl (261 kB)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached nest_asyncio2-1.7.2-py3-none-any.whl (7.8 kB)
Using cached nodeenv-1.10.0-py2.py3-none-any.whl (23 kB)
Using cached notebook_shim-0.2.4-py3-none-any.whl (13 kB)
Using cached numba-0.65.1-cp313-cp313-macosx_12_0_arm64.whl (2.7 MB)
Using cached numpy-2.4.6-cp313-cp313-macosx_14_0_arm64.whl (5.2 MB)
Using cached pandas-2.3.3-cp313-cp313-macosx_11_0_arm64.whl (10.7 MB)
Using cached pandas_stubs-3.0.3.260530-py3-none-any.whl (173 kB)
Using cached pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Using cached pathspec-1.1.1-py3-none-any.whl (57 kB)
Using cached pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
Using cached pillow-12.2.0-cp313-cp313-macosx_11_0_arm64.whl (4.7 MB)
Using cached platformdirs-4.10.0-py3-none-any.whl (22 kB)
Using cached pluggy-1.6.0-py3-none-any.whl (20 kB)
Using cached pre_commit-4.6.0-py2.py3-none-any.whl (226 kB)
Using cached prometheus_client-0.25.0-py3-none-any.whl (64 kB)
Using cached protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl (129 kB)
Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Using cached pure_eval-0.2.3-py3-none-any.whl (11 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached pylint-4.0.6-py3-none-any.whl (538 kB)
Using cached pylint_django-2.7.0-py3-none-any.whl (42 kB)
Using cached pylint_plugin_utils-0.9.0-py3-none-any.whl (11 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached pyproject_api-1.10.1-py3-none-any.whl (12 kB)
Using cached pytest-9.1.0-py3-none-any.whl (386 kB)
Using cached pytest_mock-3.15.1-py3-none-any.whl (10 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached python_discovery-1.4.2-py3-none-any.whl (33 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached python_json_logger-4.1.0-py3-none-any.whl (15 kB)
Using cached python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Using cached pyzmq-27.1.0-cp312-abi3-macosx_10_15_universal2.whl (1.3 MB)
Using cached rapidfuzz-3.14.5-cp313-cp313-macosx_11_0_arm64.whl (1.2 MB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Using cached rfc3987_syntax-1.1.0-py3-none-any.whl (8.0 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached rpds_py-2026.5.1-cp313-cp313-macosx_11_0_arm64.whl (345 kB)
Using cached scikit_learn-1.9.0-cp313-cp313-macosx_12_0_arm64.whl (8.2 MB)
Using cached scipy-1.17.1-cp313-cp313-macosx_14_0_arm64.whl (20.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached send2trash-2.1.0-py3-none-any.whl (17 kB)
Using cached shap-0.52.0-cp312-abi3-macosx_11_0_arm64.whl (490 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached slicer-0.0.8-py3-none-any.whl (15 kB)
Using cached soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Using cached stevedore-5.8.0-py3-none-any.whl (54 kB)
Using cached terminado-0.18.1-py3-none-any.whl (14 kB)
Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tinycss2-1.5.1-py3-none-any.whl (28 kB)
Using cached tomli_w-1.2.0-py3-none-any.whl (6.7 kB)
Using cached tomlkit-0.15.0-py3-none-any.whl (41 kB)
Using cached tornado-6.5.7-cp39-abi3-macosx_10_9_universal2.whl (448 kB)
Using cached tox-4.55.1-py3-none-any.whl (215 kB)
Using cached tqdm-4.68.2-py3-none-any.whl (78 kB)
Using cached traitlets-5.15.1-py3-none-any.whl (85 kB)
Using cached typer-0.26.7-py3-none-any.whl (122 kB)
Using cached types_cachetools-7.0.0.20260518-py3-none-any.whl (9.5 kB)
Using cached types_html5lib-1.1.11.20260518-py3-none-any.whl (24 kB)
Using cached types_lxml-2026.2.16-py3-none-any.whl (97 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached types_requests-2.33.0.20260518-py3-none-any.whl (21 kB)
Using cached types_tqdm-4.68.0.20260608-py3-none-any.whl (24 kB)
Using cached types_webencodings-0.5.0.20260408-py3-none-any.whl (8.7 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Using cached uri_template-1.3.0-py3-none-any.whl (11 kB)
Using cached virtualenv-21.5.0-py3-none-any.whl (4.6 MB)
Using cached wcwidth-0.8.1-py3-none-any.whl (323 kB)
Using cached webcolors-25.10.0-py3-none-any.whl (14 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Installing collected packages: webencodings, text-unidecode, pytz, pure-eval, ptyprocess, fastjsonschema, distlib, websocket-client, webcolors, wcwidth, urllib3, uri-template, tzdata, typing-extensions, types-webencodings, types-cachetools, traitlets, tqdm, tornado, tomlkit, tomli-w, tinycss2, threadpoolctl, stevedore, soupsieve, slicer, six, shellingham, send2trash, rpds-py, rfc3986-validator, rapidfuzz, pyzmq, pyyaml, pytokens, python-slugify, python-json-logger, python-dotenv, pyproject-api, pyparsing, pygments, pyflakes, pycparser, pycodestyle, psutil, protobuf, prometheus-client, pluggy, platformdirs, pillow, pexpect, pathspec, parso, pandocfilters, numpy, nodeenv, nest-asyncio2, narwhals, mypy-extensions, mistune, mdurl, mccabe, markupsafe, llvmlite, librt, lark, kiwisolver, jupyterlab-pygments, jsonpointer, json5, joblib, isort, iniconfig, idna, identify, h11, fqdn, fonttools, filelock, executing, duckdb, dill, defusedxml, decorator, debugpy, cycler, cssselect, coverage, comm, colorama, codespell, cloudpickle, charset-normalizer, cfgv, certifi, cachetools, bleach, babel, attrs, async-lru, asttokens, astroid, ast-serialize, appnope, annotated-doc, types-requests, types-html5lib, terminado, stack-data, scipy, rfc3987-syntax, rfc3339-validator, requests, referencing, python-discovery, python-dateutil, pytest, pylint, prompt-toolkit, pandas-stubs, numba, mypy, matplotlib-inline, markdown-it-py, jupyter-core, jinja2, jedi, ipython-pygments-lexers, httpcore, flake8, contourpy, cffi, black, beautifulsoup4, anyio, virtualenv, types-tqdm, types-lxml, scikit-learn, rich, pytest-mock, pylint-plugin-utils, pandas, mdit-py-plugins, matplotlib, kagglesdk, jupyter-server-terminals, jupyter-client, jsonschema-specifications, ipython, httpx, flake8-coding, arrow, argon2-cffi-bindings, typer, tox, shap, seaborn, pylint-django, pre-commit, jsonschema, isoduration, ipykernel, bandit, argon2-cffi, nbformat, nbclient, jupytext, jupyter-events, nbconvert, kaggle, jupyter-server, notebook-shim, jupyterlab-server, jupyter-lsp, jupyterlab

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176/176 [jupyterlab]5/176 [jupyterlab]0m [jupyter-server]t]
Successfully installed annotated-doc-0.0.4 anyio-4.13.0 appnope-0.1.4 argon2-cffi-25.1.0 argon2-cffi-bindings-25.1.0 arrow-1.4.0 ast-serialize-0.5.0 astroid-4.0.4 asttokens-3.0.1 async-lru-2.3.0 attrs-26.1.0 babel-2.18.0 bandit-1.9.4 beautifulsoup4-4.15.0 black-26.5.1 bleach-6.4.0 cachetools-7.1.4 certifi-2026.5.20 cffi-2.0.0 cfgv-3.5.0 charset-normalizer-3.4.7 cloudpickle-3.1.2 codespell-2.4.2 colorama-0.4.6 comm-0.2.3 contourpy-1.3.3 coverage-7.14.1 cssselect-1.4.0 cycler-0.12.1 debugpy-1.8.21 decorator-5.3.1 defusedxml-0.7.1 dill-0.4.1 distlib-0.4.3 duckdb-1.5.3 executing-2.2.1 fastjsonschema-2.21.2 filelock-3.29.4 flake8-7.3.0 flake8-coding-1.3.2 fonttools-4.63.0 fqdn-1.5.1 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 identify-2.6.19 idna-3.18 iniconfig-2.3.0 ipykernel-7.3.0 ipython-9.14.1 ipython-pygments-lexers-1.1.1 isoduration-20.11.0 isort-8.0.1 jedi-0.20.0 jinja2-3.1.6 joblib-1.5.3 json5-0.14.0 jsonpointer-3.1.1 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 jupyter-client-8.9.1 jupyter-core-5.9.1 jupyter-events-0.12.1 jupyter-lsp-2.3.1 jupyter-server-2.19.0 jupyter-server-terminals-0.5.4 jupyterlab-4.5.8 jupyterlab-pygments-0.3.0 jupyterlab-server-2.28.0 jupytext-1.19.3 kaggle-2.2.1 kagglesdk-0.1.30 kiwisolver-1.5.0 lark-1.3.1 librt-0.11.0 llvmlite-0.47.0 markdown-it-py-4.2.0 markupsafe-3.0.3 matplotlib-3.11.0 matplotlib-inline-0.2.2 mccabe-0.7.0 mdit-py-plugins-0.6.1 mdurl-0.1.2 mistune-3.2.1 mypy-2.1.0 mypy-extensions-1.1.0 narwhals-2.22.1 nbclient-0.11.0 nbconvert-7.17.1 nbformat-5.10.4 nest-asyncio2-1.7.2 nodeenv-1.10.0 notebook-shim-0.2.4 numba-0.65.1 numpy-2.4.6 pandas-2.3.3 pandas-stubs-3.0.3.260530 pandocfilters-1.5.1 parso-0.8.7 pathspec-1.1.1 pexpect-4.9.0 pillow-12.2.0 platformdirs-4.10.0 pluggy-1.6.0 pre-commit-4.6.0 prometheus-client-0.25.0 prompt-toolkit-3.0.52 protobuf-6.33.6 psutil-7.2.2 ptyprocess-0.7.0 pure-eval-0.2.3 pycodestyle-2.14.0 pycparser-3.0 pyflakes-3.4.0 pygments-2.20.0 pylint-4.0.6 pylint-django-2.7.0 pylint-plugin-utils-0.9.0 pyparsing-3.3.2 pyproject-api-1.10.1 pytest-9.1.0 pytest-mock-3.15.1 python-dateutil-2.9.0.post0 python-discovery-1.4.2 python-dotenv-1.2.2 python-json-logger-4.1.0 python-slugify-8.0.4 pytokens-0.4.1 pytz-2026.2 pyyaml-6.0.3 pyzmq-27.1.0 rapidfuzz-3.14.5 referencing-0.37.0 requests-2.34.2 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 rfc3987-syntax-1.1.0 rich-15.0.0 rpds-py-2026.5.1 scikit-learn-1.9.0 scipy-1.17.1 seaborn-0.13.2 send2trash-2.1.0 shap-0.52.0 shellingham-1.5.4 six-1.17.0 slicer-0.0.8 soupsieve-2.8.4 stack-data-0.6.3 stevedore-5.8.0 terminado-0.18.1 text-unidecode-1.3 threadpoolctl-3.6.0 tinycss2-1.5.1 tomli-w-1.2.0 tomlkit-0.15.0 tornado-6.5.7 tox-4.55.1 tqdm-4.68.2 traitlets-5.15.1 typer-0.26.7 types-cachetools-7.0.0.20260518 types-html5lib-1.1.11.20260518 types-lxml-2026.2.16 types-requests-2.33.0.20260518 types-tqdm-4.68.0.20260608 types-webencodings-0.5.0.20260408 typing-extensions-4.15.0 tzdata-2026.2 uri-template-1.3.0 urllib3-2.7.0 virtualenv-21.5.0 wcwidth-0.8.1 webcolors-25.10.0 webencodings-0.5.1 websocket-client-1.9.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
source venv/bin/activate && python3.13 -m ipykernel install --user --name py311 --display-name "Python 3.13"
Installed kernelspec py311 in /Users/mcdaniel/Library/Jupyter/kernels/py311
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/mcdaniel/Desktop/gh/fswl/netflix-writers/netflix/fetch/__main__.py", line 3, in <module>
    from .fetch_imdb import main as fetch_imdb
  File "/Users/mcdaniel/Desktop/gh/fswl/netflix-writers/netflix/fetch/fetch_imdb.py", line 16, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/mcdaniel/Desktop/gh/fswl/netflix-writers/netflix/build/__main__.py", line 3, in <module>
    from netflix.build.dataset import create_dataset
  File "/Users/mcdaniel/Desktop/gh/fswl/netflix-writers/netflix/build/dataset.py", line 14, in <module>
    import duckdb
ModuleNotFoundError: No module named 'duckdb'

In [2]:

import pandas as pd

imdb = pd.read_csv("netflix/data/imdb.titles.composite.csv")
netflix = pd.read_csv("netflix/data/netflix.titles.composite.csv")
tmdb = pd.read_csv("netflix/data/tmdb.titles.v3.csv")

print(imdb.shape, netflix.shape, tmdb.shape)

(297610, 15) (691, 13) (168639, 29)

## Exercise 1 — First Look at Popularity
Find the top shows in each dataset.

In [3]:

# Top Netflix shows by viewing hours
netflix.sort_values("netflix_viewing_hours", ascending=False).head(10)

,key,netflix_viewing_hours,netflix_weeks,netflix_year_hint,netflix_title,netflix_clean_title,tmdb_title,tmdb_popularity,tmdb_vote_average,tmdb_vote_count,imdb_title,imdb_averageRating,imdb_numVotes
661,st_th,2874260000,13,2022,Stranger Things,stranger things,Stranger Things,185.711,8.624,16161.0,Stranger Things,NaN,NaN
396,ga_sq,2289500000,20,2021,Squid Game,squid game,Squid Game,115.587,7.831,13053.0,Squid Game,NaN,NaN
549,ma,1446260000,16,2021,Manifest,manifest,Manifest,111.411,7.728,1312.0,Manifest,8.3,4243.0
447,he_mo,1170200000,14,2021,Money Heist,money heist,Money Heist,96.354,8.257,17836.0,Money Heist,8.2,609923.0
167,br,1108800000,11,2021,Bridgerton,bridgerton,Bridgerton,71.308,8.143,2045.0,Bridgerton,7.5,229326.0
103,ar_ca_co,793740000,25,2022,Café con aroma de mujer,caf con aroma de mujer,Café con Aroma de Mujer,20.710,7.500,382.0,Café con aroma de mujer,8.6,106.0
690,yo,777480000,8,2021,You,you,続・アタッカーYOU 金メダルへの道,7.101,2.500,2.0,You,6.1,152.0
686,wi,757350000,6,2021,Windfall,windfall,Windfall,3.813,0.000,0.0,Windfall,NaN,NaN
607,oz,751600000,13,2022,Ozark,ozark,Ozark,68.006,8.244,1968.0,Ozark,8.4,393348.0
69,al_ar_us,659510000,11,2022,All of Us Are Dead,all of us are dead,All of Us Are Dead,107.108,8.354,3335.0,All of Us Are Dead,7.6,91672.0

In [4]:

# Top IMDb shows by rating
imdb.sort_values("averageRating", ascending=False).head(10)

,tconst,titleType,primaryTitle,originalTitle,startYear,endYear,runtimeMinutes,genres,title_key,averageRating,numVotes,all_akas,cast,directors,writers
237695,tt28305644,tvSeries,EDP Watch,EDP Watch,2023,\N,\N,Crime,atch,9.8,103.0,edp watch,Demarcus Cousins III | Skeeter Jean | Kaizer K...,nm15017595,nm15017595
223185,tt24228604,tvSeries,OdBita Pot,OdBita Pot,2022,2026,\N,Adventure,dita ot,9.8,1340.0,odbita pot,Bit Sever | Anze Sever,nm7689797,nm7689797
297553,tt34888713,tvSeries,The bomb has been planted,The bomb has been planted,2024,\N,\N,Documentary,he bomb has been planted,9.7,74.0,the bomb has been planted,NaN,nm15670960,"nm16799280,nm15670960"
57340,tt8103440,tvSeries,Herne Katha,Herne Katha,2018,\N,\N,"Documentary,Short",erne atha,9.7,411.0,herne katha,Kamal Kumar | Bidhya Chapagain,"nm9678594,nm9678593","nm9678593,nm9678594"
150379,tt12831434,tvSeries,The Simonetta Lein Show,The Simonetta Lein Show,2020,2026,\N,Talk-Show,he imonetta ein how,9.7,810.0,the simonetta lein show,Karyn Parsons | Lori Greiner | Gabriela Gonzal...,\N,\N
219247,tt2354568,tvSeries,Raja Shivchhatrapati,Raja Shivchhatrapati,2008,2009,22,"Biography,History",aja hivchhatrapati,9.6,742.0,राजा शिवछत्रपती | raja shivchhatrapati,Yatin Karyekar | Avinash Narkar | Mrinal Kulka...,"nm7080093,nm0220834","nm0220834,nm13150997,nm2590010"
48949,tt7151672,tvSeries,Choufli Hal,Choufli Hal,2005,2009,\N,Comedy,houfli al,9.6,3380.0,choufli hal,Mouna Noureddine | Kaouther Belhaj | Abdelghan...,nm9140277,nm9140285
152514,tt13045860,tvSeries,Hiç Komik Degil,Hiç Komik Degil,2011,2021,\N,Comedy,i omik egil,9.6,593.0,hiç komik değil | hiç komik degil,Ercan Taner | Bora Aksu | Burakcan Kocabay | B...,nm4706688,nm4706688
233550,tt27677007,tvSeries,Impossible Escape,Fuga Impossível,2015,2020,\N,"Adventure,Animation,Crime",mpossible scape,9.6,317.0,escapada imposible | impossible escape | fuga ...,Tarik Felipe Pacanhan | Rafael Lange | Rafael ...,"nm11875945,nm11875944","nm11875945,nm11875944"
172761,tt14810290,tvSeries,The Life Series,The Life Series,2021,\N,\N,Action,he ife eries,9.6,213.0,the life (minecraft) | the life series | third...,Oliver Brotherhood | Ethoslab | Cleo | Charles...,nm9586733,nm9586733

In [5]:

# Top TMDb shows by popularity
tmdb.sort_values("popularity", ascending=False).head(10)

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
1771,63770,The Late Show with Stephen Colbert,9,1419,en,205,6.495,Stephen Colbert brings his signature satire an...,False,/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg,...,NaN,"Comedy, Talk","Jon Stewart, Stephen Colbert, Tom Purcell, Chr...",en,CBS,US,English,"Spartina Productions, CBS Studios",United States of America,41
3035,215803,Batang Quiapo,2,178,tl,99,7.030,A young man rises to be one of the biggest out...,False,/jIV5weV19wH02rnuWyMtYI4dYC8.jpg,...,NaN,"Action & Adventure, Comedy, Drama",NaN,tl,"TV5, Kapamilya Channel",PH,NaN,"ABS-CBN Entertainment, Dreamscape Entertainmen...",Philippines,0
2285,94722,Tagesschau,72,20839,de,145,7.500,"German daily news program, the oldest still ex...",False,/jWXrQstj7p3Wl5MfYWY6IHqRpDb.jpg,...,NaN,News,NaN,de,ARD,DE,Deutsch,NDR,Germany,15
3593,14981,The Late Late Show with Craig Ferguson,11,2057,en,77,7.065,The Late Late Show with Craig Ferguson is an A...,False,/m0bV3qBiJBBlpFaaKjwHo13MVjm.jpg,...,NaN,"Comedy, Talk",NaN,en,CBS,US,English,NaN,United States of America,60
4565,2261,The Tonight Show Starring Johnny Carson,31,2924,en,51,7.800,The Tonight Show Starring Johnny Carson is a t...,False,/qFfWFwfaEHzDLWLuttWiYq7Poy2.jpg,...,NaN,Talk,"Steve Allen, Sylvester Weaver",en,NBC,US,English,"NBC Productions, Carson Productions",United States of America,60
4651,81329,Chronicles of the Sun,5,1252,fr,49,7.510,NaN,False,/rj3jBAZwPiOgkwAy1205MAgLahj.jpg,...,NaN,Soap,NaN,fr,France 2,FR,Français,"France Télévisions, Epeios Productions, France...",France,26
1600,59941,The Tonight Show Starring Jimmy Fallon,11,1233,en,234,6.038,After Jay Leno's second retirement from the pr...,False,/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg,...,Tonight's just getting started.,"Comedy, Talk",Jimmy Fallon,en,NBC,US,English,"Broadway Video, Universal Television, Electric...",United States of America,45
7314,244643,El amor no tiene receta,1,91,es,23,8.300,"Paz Roble, a kind, hard-working and honest wom...",False,/bIhmqQNXcyWRzH153d3jaCbLTy3.jpg,...,NaN,"Action & Adventure, Family, Drama, Soap, Comed...","Juan Osorio Ortiz, Pablo Ferrer García-Travesí...",es,"Univision, Las Estrellas, ViX","MX, US",Español,"TelevisaUnivision Mexico, Televisa",Mexico,50
8641,225660,Pira-Pirasong Paraiso,2,78,tl,17,7.000,A con artist takes on the job of pretending to...,False,/2N4LXvTkUwPRkbvyzdmzvtnCHgR.jpg,...,NaN,NaN,NaN,"en, tl","TV5, Kapamilya Channel",PH,English,Dreamscape Entertainment Television,Philippines,0
7217,91759,Come Home Love: Lo and Behold,1,2107,cn,23,4.565,"Hung Sue Gan starting from the bottom, establi...",False,/ohJTnu93hJ0Uonl86Wn3mOSlWXN.jpg,...,NaN,"Family, Comedy, Drama",NaN,cn,TVB Jade,HK,广州话 / 廣州話,TVB,Hong Kong,22

## Exercise 2 — What Does “Popular” Mean?
Compare different popularity signals.

In [6]:

netflix["netflix_viewing_hours"].describe()

count    6.910000e+02
mean     6.919165e+07
std      1.879555e+08
min      1.130000e+06
25%      8.930000e+06
50%      2.028000e+07
75%      5.560000e+07
max      2.874260e+09
Name: netflix_viewing_hours, dtype: float64

In [7]:

imdb["averageRating"].describe()

count    47881.000000
mean         6.854583
std          1.293971
min          1.000000
25%          6.300000
50%          7.100000
75%          7.700000
max          9.800000
Name: averageRating, dtype: float64

In [8]:

tmdb["popularity"].describe()

count    168639.000000
mean          5.882644
std          42.023216
min           0.000000
25%           0.600000
50%           0.857000
75%           2.431500
max        3707.008000
Name: popularity, dtype: float64

## Exercise 3 — High Views vs High Ratings

In [9]:

netflix.sort_values("netflix_viewing_hours", ascending=False).head(5)[["netflix_title","netflix_viewing_hours"]]

       netflix_title  netflix_viewing_hours
661  Stranger Things             2874260000
396       Squid Game             2289500000
549         Manifest             1446260000
447      Money Heist             1170200000
167       Bridgerton             1108800000

## Exercise 4 — Genre Power

In [10]:

imdb["genres"].dropna().head()

0    Comedy,Drama
1     Crime,Drama
2     Documentary
3          Comedy
4      Reality-TV
Name: genres, dtype: object

## Exercise 5 — Language & Global Reach

In [11]:

tmdb["original_language"].value_counts().head(10)

original_language
en    76304
zh    14422
ja    14048
ko     7820
de     7712
fr     7290
es     5602
pt     3551
ru     2963
nl     2923
Name: count, dtype: int64

## Exercise 6 — Short vs Long Shows

In [12]:

tmdb[["number_of_seasons","popularity"]].corr()

                   number_of_seasons  popularity
number_of_seasons           1.000000    0.189827
popularity                  0.189827    1.000000

## Exercise 7 — Binge Effect

In [13]:

netflix[["netflix_weeks","netflix_viewing_hours"]].corr()

                       netflix_weeks  netflix_viewing_hours
netflix_weeks               1.000000               0.634786
netflix_viewing_hours       0.634786               1.000000

## Exercise 8 — Cast Impact

In [14]:

imdb["cast_count"] = imdb["cast"].fillna("").apply(lambda x: len(x.split("|")))
imdb[["cast_count","averageRating"]].corr()

               cast_count  averageRating
cast_count        1.00000       -0.07761
averageRating    -0.07761        1.00000

## Exercise 9 — The Perfect Show Profile

Write your ideal show recipe using evidence from the dataset.

## Exercise 10 — Build a Hit Score

In [15]:

df = netflix.copy()

df["hit_score"] = (
    df["netflix_viewing_hours"] / df["netflix_viewing_hours"].max()
)

df.sort_values("hit_score", ascending=False).head(10)

,key,netflix_viewing_hours,netflix_weeks,netflix_year_hint,netflix_title,netflix_clean_title,tmdb_title,tmdb_popularity,tmdb_vote_average,tmdb_vote_count,imdb_title,imdb_averageRating,imdb_numVotes,hit_score
661,st_th,2874260000,13,2022,Stranger Things,stranger things,Stranger Things,185.711,8.624,16161.0,Stranger Things,NaN,NaN,1.000000
396,ga_sq,2289500000,20,2021,Squid Game,squid game,Squid Game,115.587,7.831,13053.0,Squid Game,NaN,NaN,0.796553
549,ma,1446260000,16,2021,Manifest,manifest,Manifest,111.411,7.728,1312.0,Manifest,8.3,4243.0,0.503176
447,he_mo,1170200000,14,2021,Money Heist,money heist,Money Heist,96.354,8.257,17836.0,Money Heist,8.2,609923.0,0.407131
167,br,1108800000,11,2021,Bridgerton,bridgerton,Bridgerton,71.308,8.143,2045.0,Bridgerton,7.5,229326.0,0.385769
103,ar_ca_co,793740000,25,2022,Café con aroma de mujer,caf con aroma de mujer,Café con Aroma de Mujer,20.710,7.500,382.0,Café con aroma de mujer,8.6,106.0,0.276155
690,yo,777480000,8,2021,You,you,続・アタッカーYOU 金メダルへの道,7.101,2.500,2.0,You,6.1,152.0,0.270497
686,wi,757350000,6,2021,Windfall,windfall,Windfall,3.813,0.000,0.0,Windfall,NaN,NaN,0.263494
607,oz,751600000,13,2022,Ozark,ozark,Ozark,68.006,8.244,1968.0,Ozark,8.4,393348.0,0.261493
69,al_ar_us,659510000,11,2022,All of Us Are Dead,all of us are dead,All of Us Are Dead,107.108,8.354,3335.0,All of Us Are Dead,7.6,91672.0,0.229454

## Bonus — Polti's 36 Dramatic Situations
Choose ONE situation from Polti's framework and design a TV series around it.

Explain how it could become a hit using dataset evidence.